FROM node:20.19.4-alpine3.21 as build

RUN mkdir /app

COPY . /app

WORKDIR /app

RUN yarn config set registry https://registry.npmmirror.com && \
    yarn cache clean && \
    yarn install && \
    yarn build && \
    tar zcf build.tar.gz ./build

FROM nginx:1.28.0 as release

RUN sed -i "s@http://deb.debian.org/debian@http://mirrors.cloud.tencent.com/debian@g" /etc/apt/sources.list.d/debian.sources

RUN apt-get update && \
    apt-get install -y git && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get clean && \
    mkdir /app

COPY --from=build /app/build.tar.gz /app

RUN tar zxf /app/build.tar.gz -C /app && \
    mv /app/build/* /app && \
    rm -rf /app/build* && \
    rm -rf /etc/nginx/conf.d/default.conf

COPY ./w8t.conf /etc/nginx/conf.d

WORKDIR /etc/nginx/

EXPOSE 80

CMD ["nginx","-g","daemon off;"]
